### ISSUE TITLE
More than 8 Streams by oscam

### ISSUE THREAD

**Issue by gigo1988** [E2OpenPlugins/e2openplugins#10]
Hello MILO,

i´m new in the linux world and have a little trouble. I´ve see that you have wrote something with demuxing by low buffer and so on. But i didnt realy understand.
My Problem is that i want to stream more than 8 streams at home from my stb to android devices from my paytv but my oscam cant do that. Where im able to do that. Please sorry if its the wrong place here to ask for this issue.

**Comment by WanWizard** [comment]
This is indeed the wrong place. Use the forum of your image provider for questions.
